import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;

/// TODO: replace with the real values from the Firebase console
/// (Project settings → Your apps → Android app `com.ksvl.admin_app`).
/// Generated by hand until `google-services.json` / the FlutterFire CLI
/// output is available.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzjDV5EdaKfQvc2bFPRLh9rjvrr0k-5jA',
    appId: '1:604154597035:android:4437e466b3167aee80f1ee',
    messagingSenderId: '604154597035',
    projectId: 'ksvl-naturals',
    storageBucket: 'ksvl-naturals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO',
    appId: 'TODO',
    messagingSenderId: 'TODO',
    projectId: 'ksvl-naturals',
    iosBundleId: 'com.ksvl.adminApp',
  );
}
